### PR TITLE
Add custom draw style object array

### LINKED ISSUE #310: Make all point and polygon vertices more visible
- [x] Active vertices should be bigger and higher contrast
- [x] Non-active midpoints should be also made more visible and should visibly distinct from the active vertices

### PR DESCRIPTION
**Pull request by hannahkates**
This PR adds a custom custom draw style object array so that polygon vertices will be more visible and prominent.

Closes #310.

### CODE REVIEW

**Comment by allthesignals** [comment]
So the proposed changes don't work?

**Comment by chriswhong** [comment]
@allthesignals is adding custom draw styles in the annotation feature, we should probably align these two once that's more mature.

**Comment by chriswhong** [comment]
working on broken tests

**Comment by andycochran** [comment]
Closing this, as fixing the merge conflicts does not work. The draw styles have changed a lot in `develop` since this PR was opened. They're now happening a different way in other files. I did copy this PR's `drawStyles` array into a comment on #310, so they can be referenced in another attempt to resolve this.

**Pull request closed without merging**
