### PR TITLE
Dashboard improvements and misc minor edits

### LINKED ISSUE #222: Update language on creation form
- Project number is optional
- Reference PAS

### LINKED ISSUE #304: Get rid of "About" route and dummy saved project menu

### LINKED ISSUE #320: Add header on dashboard that makes it obvious these are the user's proposed changes

### LINKED ISSUE #321: Add email to self button on project dashboard

### PR DESCRIPTION
**Pull request by hannahkates**
This PR
- [dashboard] Adds an email button on the project dashboard that uses a template to fill in the project name and project ID for the URL in the subject and body of the email.
- [dashboard] Adds a header above the users proposed geoms.
- [entire app] Removes the "About" and "My projects" items from the nav bar.
- [new project form] Adds a reference to the PAS number for the "project number" and emphasizes that it's optional, since this has been confusing for users.

Closes #304 . Closes #321. Closes #320 . Closes #222 

@andycochran how do you think the design can be improved?

image

### CODE REVIEW

**Comment by andycochran** [comment]
Also, if we're not going to remove `{{banner.nav}}` altogether, we should pass `responsiveNav=false` to `{{labs-ui/site-header}}` so that there's no menu button on mobile.

**Comment by allthesignals** [comment]
@hannahkates what's going on with tests? Looks like commits are being pushed with broken tests

**Comment by andycochran** [comment]
> `add modal scss`

I assume ^this is copied from ZAP? Do we need this if we're using an Ember Tooltips Popover?

**Comment by andycochran** [comment]
@hannahkates Yeah. You can pass this off to me if you want.

**Comment by hannahkates** [comment]
Thanks @andycochran , unassigning myself.

**Pull request merged**
