### PR TITLE
92-citations-timestamp (WIP--Want to hear thoughts on fitting data sources into legend)

### LINKED ISSUE #92: Add data citation and timestamp for map creation

### PR DESCRIPTION
**Pull request by trbmcginnis**
-Adding the project URL to the bottom right corner of the print page

-Adding data sources list into the legend of the area map. This data is pulled from labs-layers meta. I reduced these down a little so that they would fit into the legend. I made the URL links just the "link out" symbol instead of the actual URL text.

ISSUE: Right now I am having trouble fitting all of the data sources into the legend when the paper size is set to "Letter." "Tabloid" is working fine for both portrait and landscape. 

^^^Interested in chatting with team about how to solve this problem since right now it looks like we're trying to fit a lot of information into limited space on the legend. 

Closes #92

### CODE REVIEW

**Comment by trbmcginnis** [comment]
image

**Comment by allthesignals** [comment]
Merging this will also partly fix #194 because this PR provides model definition for Source

**Comment by allthesignals** [comment]
@andycochran any thoughts on this issue Taylor's having? Says it's a lot of info from the sources.

**Comment by andycochran** [comment]
As the output of this app is really designed for print, I'm not sure it makes sense to have external link icons (which don't function on paper). 

How helpful is the description or URL to the end user? What seems most important to me is listing the `updated_at` date for each source so you can compare source dates of maps. But I'm not sure what those dates would appear alongside. 

Maybe the Layer Group API's source `meta` object needs a short `title` that matches the source's `id` (e.g. `zoning-districts`="Zoning Districts" ; `transportation`="Transportation" ; `digital-citymap`="City Map"). 

Then we could list the data sources in a shorter way: 
> Zoning Districts (updated 6 April, 2018), Transportation (updated…

And if we simply list `https://layers-api.planninglabs.nyc/v1/sources` as the source (which includes the detailed descriptions), you can check it to see if the source has been updated since the map was printed. 

@chriswhong Do you have any thoughts on this?

**Comment by allthesignals** [comment]
> Maybe the Layer Group API's source meta object needs a short title that matches the source's id (e.g. zoning-districts="Zoning Districts" ; transportation="Transportation" ; digital-citymap="City Map").

Could this not be inferred from the source's related `layer-group`? 

Also, the issue Taylor is having here is more around listing a large number of sources. Is your advice to simplify the listing (comma-separated vs bullets)? Is there something we can do in the short-term to get this merged without needing to make changes to the data structure?

**Comment by andycochran** [comment]
You're right; we don't need to change the `meta`. A computed prop could assign a name to each source and append it to the comma-separated list. I'd suggest markup like this: 

```
<section class="legend-section">
  <p class="text-tiny">
    <strong>Source Data:</strong>
    {{#each sources as |source index|}}
      {{if index ", "}}{{source.name}} ({{source.date}})
    {{/each}}
  </p>
</section>
```

**Comment by allthesignals** [comment]
Cool - @trbmcginnis make sense ?

**Comment by trbmcginnis** [comment]
Yes, I can work on this today !

**Comment by trbmcginnis** [comment]
Started working on this this morning, just to keep you updated on where I'm at. Right now, I have this in the template as this: 

<section>
  <div>
    <h2 class="legend-section-header">Data Sources</h2>
        {{#each mapConfiguration.sources as |source|}}
            {{~if source.id ", "}}<strong><span class="dark-gray text-small">{{source.id}}</span></strong>
            {{~if source.meta.updated_at ", "}}<span class="dark-gray text-small">Updated on: {{source.meta.updated_at}}</span>
          {{/each}}
  </div>
</section>


It's showing up fine but the titles for each data layer is dasherized (e.g. digital-citymap), so I made a helper to fix that (the helper file is edit-source-id), where it replaces the hyphen with a space and capitalizes the first letter of each word. I'm getting an error that says "Cannot assign to read only property 'length' of object '[object Array]'"

I'm assuming this has to do with trying to edit the layer-groups "id" in the template while I'm pulling form the source model. So I tried pulling from mapForm.model.layerGroups instead of mapConfiguration.sources, but that wasn't working either. 

@andycochran and @allthesignals  You mentioned needing a computed property for this. i'm assuming the computed property just pulls from the associated layer-groups (the map-form model layer-groups) id and assigns a new id to each one that is formatted with no hyphen and capitalized (Digital Citymap)? Would that fix this read-only problem I'm getting? 

 Need to run to work now, but I'm going to keep working on this tonight!

**Comment by andycochran** [comment]
Maybe we should avoid programmatically changing to uppercase letters — we'd get e.g. "Paws" and "Pluto". It might be better to just show the raw source ID as it appears in the JSON, and also provide a link to https://layers-api.planninglabs.nyc/v1/sources.

**Comment by andycochran** [comment]
It can be clickable. That'd be useful if you print to PDF.

**Pull request merged**
